---
- name: 'Verify docker-compose version'
  shell: 'docker-compose --version'
  register: docker_compose_current_version
  changed_when: false
  failed_when: false


- name: 'Remove old version of docker-compose'
  become: True
  file:
    path: '{{ docker_compose_path }}'
    state: absent
  when: >
    docker_compose_current_version.stdout is defined
    and
    docker_compose_version not in docker_compose_current_version.stdout


- name: 'Install docker-compose'
  become: True
  get_url:
    url: '{{ docker_compose_url }}'
    dest: '{{ docker_compose_path }}'
    mode: 0755